# Setup:
# brew install chromaprint
# pip install discogs_client requests pylast pyacoustid
directory: ~/.config/beets/musiclib

import:
  write: yes
  move: yes
  resume: ask
  timid: yes

art_filename: cover

match:
  preferred:
    countries: ['US', 'GB|UK', 'NO']
    media: ['Digital Media|File', 'CD']
    original_year: yes

item_fields:
  disc_and_track: u'%02i-%02i' % (disc, track) if
                  disctotal > 1 else u'%02i' % (track)

paths:
  default: $format/%if{$albumartist_sort,$albumartist_sort,$albumartist} [%if{$original_year,$original_year,$year}%if{$original_month,-$original_month,%if{$month,-$month}}] $album/$disc_and_track $title
  genre:Podcast: podcast/$album/$disc_and_track $title
  comp: $format/Various Artists [%if{$original_year,$original_year,$year}%if{$original_month,-$original_month,%if{$month,-$month}}] $album%aunique{}/$track $title
  singleton: $format/Nonsense/$artist - $title

per_disc_numbering: yes
ignore: .AppleDouble ._* *~ .DS_Store

plugins: chroma inline discogs info lastgenre fetchart lyrics scrub #convert

scrub:
  auto: no

convert:
  auto: no
  dest: ~/.config/beets/musiclib-lossy
  embed: yes
  never_convert_lossy_files: yes

fetchart:
  auto: yes
  cautious: true
  cover_names: cover front back

lyrics:
  auto: yes
  fallback: null
  google_API_key: null
  google_engine_ID: null

lastgenre:
  auto: yes
  canonical: yes
  count: 1
  fallback: ''
  force: yes
  source: album

