require('core.plugin_config.gitsigns')
-- require('core.plugin_config.kind')
require('core.plugin_config.lsp')
require('core.plugin_config.lualine')
require('core.plugin_config.luasnip')
require('core.plugin_config.mini_comment')
require('core.plugin_config.mini_surround')
require('core.plugin_config.neo_tree')
require('core.plugin_config.neogit')
-- require('core.plugin_config.oil')
require('core.plugin_config.telescope')
require('core.plugin_config.theme-onedark')
require('core.plugin_config.treesitter')
require('core.plugin_config.which_key')
