add_newline = true
command_timeout = 1000
scan_timeout = 200
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$docker_context\
$memory_usage\
$aws\
$gcloud\
$openstack\
$crystal\
$env_var\
$custom\
$battery\
$cmd_duration\
$fill\
$direnv\
$kubernetes\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

[directory]
read_only = ''
# Dirs, not characters
truncation_length = 5
truncation_symbol = '…/'
truncate_to_repo = false

[aws]
symbol = '󰸏'
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
disabled = false
[aws.region_aliases]
eu-central-1 = 'euc1'
eu-north-1   = 'eun1'
eu-south-1   = 'eus1'
eu-west-1    = 'euw1'
eu-west-2    = 'euw2'
eu-west-3    = 'euw3'
us-east-1    = 'use1'
us-east-2    = 'use2'
us-west-1    = 'usw1'
us-west-2    = 'usw2'

[battery]
disabled = true

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = "[󱎫$duration]($style)"

[conda]
symbol = ''
format = '\[[$symbol$environment]($style)\]'

[crystal]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[direnv]
format = '\[[$symbol $loaded/$allowed]($style)\]'
symbol = ''
style = '#ff9900'
detect_extensions = []
detect_files = ['.envrc']
detect_folders = []
allowed_msg = ''
denied_msg = ''
loaded_msg = ""
unloaded_msg = ''
disabled = false

[docker_context]
symbol = ''
format = '\[[$symbol$context]($style)\]'
disabled = true

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
symbol = ''
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[erlang]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[fill]
symbol = ' '

[gcloud]
symbol = '󱇶'
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol = ''
format = '(\[[$symbol$branch]($style)\])'

[git_state]
format = '(\[[$state( $progress_current/$progress_total)]($style)\])'
cherry_pick = ''
merge = ''

[git_status]
format = '(\[$all_status$ahead_behind\])'

ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '[](green)'

conflicted = '[ﰸ${count}](red)'
modified = '[${count}](yellow)'
staged = '[✹${count}](green)'
untracked = '[?${count}](red)'

[golang]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[helm]
symbol = '󰷀'
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = ''
format = '\[[$symbol$branch]($style)\]'

[hostname]
ssh_only = true
format = '@[$hostname]($style)'
disabled = false

[java]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[kotlin]
symbol = '󱈙'
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
symbol = ''
format = '\[[$symbol$context(/$namespace)]($style)\]'
style = 'bold blue'
disabled = false

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = true

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = ''
disabled = true

[memory_usage]
symbol = '󰍛'
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nim]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = ''
format = '\[[$symbol$state(\($name\))]($style)\]'
impure_msg = "ι"
pure_msg = "ρ"

[nodejs]
symbol = '󰎙'
format = '\[[$symbol($version)]($style)\]'

[ocaml]
symbol = ''
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
symbol = '󰏓'
format = '\[[$symbol$version]($style)\]'

[perl]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = ''
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[shell]
fish_indicator = '󰈺'
bash_indicator = '󱆃'
zsh_indicator = '󱓞'
unknown_indicator = ''
style = 'cyan bold'
disabled = false

[shlvl]
symbol = ""

[swift]
symbol = 'ﯣ'
format = '\[[$symbol($version)]($style)\]'

[terraform]
symbol = '󱁢'
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '[$user]($style)'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
symbol = ''
format = '\[[$symbol($version)]($style)\]'
